Add Transliteration feature in tts-middleware
skit-ai/tts-middleware pull request #7
Opened 2022-07-11 10:18 UTC by iamsh4shank

In TTS middleware, add the functionality of transliteration for Hindi VTTS.

Here we are using the [Indic-trans](https://github.com/indic-transliteration/indic_transliteration_py) library that generated the proper utterance for Hindi to English

2022-07-11 10:34 UTC, prashantskit commented on tts_middleware/core.py
> +        trans = Transliterator(source=lang, target='eng', build_lookup=True)
Shouldn't the target language be "hin"

2022-07-11 11:27 UTC, iamsh4shank commented on tts_middleware/core.py
> +        trans = Transliterator(source=lang, target='eng', build_lookup=True)
ok, I got it, I will modify this

2022-07-13 05:57 UTC, pskrunner14 requested changes

2022-07-13 05:57 UTC, pskrunner14 commented on tts_middleware/core.py
> +    for key in lang_code:
Can we use filter, map, and join functions to make this code cleaner?

2022-07-13 05:57 UTC, pskrunner14 commented on tts_middleware/core.py
> +    trans = Transliterator(source='eng', target='hin', build_lookup=True)
You're assuming the target language is always `hi`. Let's use the `language_code` parameter and only transliterate when it actually is `hi`.

2022-07-13 05:57 UTC, pskrunner14 commented on tts_middleware/core.py
>      def _tts(text: str, language_code: str) -> Audio:
Maybe add a flag parameter for toggling transliteration? We don't always want to trigger transliteration

2022-07-13 05:57 UTC, pskrunner14 commented on tts_middleware/core.py
> +            trans_text += f'{trans.transform(key)} '
Let's also test the transform function for performance. If it turns out to be slower than expected, we should think of optimizations like caching and parallelizing the call.

2022-07-13 15:08 UTC, iamsh4shank commented on tts_middleware/core.py
> +            trans_text += f'{trans.transform(key)} '
Sure as of now I tested for a few utterance from the sheet and performed quite fast with them

2022-07-13 15:09 UTC, iamsh4shank commented on tts_middleware/core.py
>      def _tts(text: str, language_code: str) -> Audio:
Ok sure

2022-07-13 15:13 UTC, iamsh4shank commented
@pskrunner14 did the following changes can you review it once, thank you :)

2022-07-15 11:17 UTC, pskrunner14 requested changes

2022-07-15 11:17 UTC, pskrunner14 commented on tts_middleware/core.py
> +        if transliterate and language_code == 'hin':
Language code check should be for `hi`, maybe create a mapping that maps this to `hin`

2022-07-15 11:17 UTC, pskrunner14 commented on tts_middleware/core.py
> +    for word in text.split(" "):
For loop will be really slow for our use case. Let's move to map and join

2022-07-15 11:18 UTC, pskrunner14 commented
We're also moving to google transliteration API I'm assuming? @iamsh4shank

2022-07-16 16:16 UTC, iamsh4shank commented
@pskrunner14 modified the code with the new transliteration API

2022-07-20 12:49 UTC, pskrunner14 requested changes

2022-07-20 15:22 UTC, iamsh4shank commented on tts_middleware/core.py
> +        return transliterate_text(word, lang_code)
* Processing time is around 0.37 seconds 
* There is no such direct limit that is mentioned.

2022-07-20 15:24 UTC, iamsh4shank commented
@pskrunner14 Done, let me know if there are any other changes.

2022-07-21 06:58 UTC, prashantskit commented on tts_middleware/core.py
> +        return transliterate_text(word, lang_code)
the processing time is after parallelising with threads?

2022-07-21 07:04 UTC, prashantskit commented on tts_middleware/text.py
> +    with ThreadPoolExecutor(max_workers=8) as executor:
remove the hardcoded value for workers. Do a check on the cores available and limit it to 8.

2022-07-22 13:05 UTC, pskrunner14 commented
Have made a pre-release with this feature, will integration test it with tts-service later today and do a stable release.

2022-07-22 13:06 UTC, pskrunner14 commented
@prashantskit one thing I'm concerned about here is the total pipeline latency, this will be a considerable hit to our sub ~600ms goal

2022-07-22 13:33 UTC, prashantskit commented
> 

It does but we can implement cache and single API call to fetch the transliteration to speed it up.

2022-07-27 06:22 UTC, merged

2022-07-27 06:23 UTC, pskrunner14 commented
@iamsh4shank in the future, please create branches on this same org repo and create MR instead of forking and creating PR.

2022-07-27 06:56 UTC, iamsh4shank commented
Sure will take care of this